---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	_init(_init)
	route(route)
	diagnosis(diagnosis)
	planner(planner)
	tool_agent(tool_agent)
	chat_answer(chat_answer)
	expert_a(expert_a)
	expert_b(expert_b)
	judge(judge)
	revise_experts(revise_experts)
	feedback(feedback)
	__end__([<p>__end__</p>]):::last
	__start__ --> _init;
	_init --> route;
	diagnosis -.-> __end__;
	diagnosis -.-> planner;
	expert_a -.-> __end__;
	expert_a -.-> judge;
	expert_b --> judge;
	feedback --> expert_a;
	judge -.-> feedback;
	judge -.-> revise_experts;
	planner --> tool_agent;
	revise_experts -.-> expert_a;
	revise_experts -.-> expert_b;
	route -.-> diagnosis;
	route -.-> tool_agent;
	tool_agent -.-> chat_answer;
	tool_agent -.-> expert_a;
	tool_agent -.-> expert_b;
	chat_answer --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
